### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sorenjensen** [Enngage/ngx-masonry-gallery#41]
I get this error 

ERROR TypeError: ue is not a constructor
    at te.initMasonry (main.js:1:17531)
    at te.ngAfterViewInit (main.js:1:16592)
    at Pe (main.js:1:568249)
    at he (main.js:1:568070)
    at L (main.js:1:567798)
    at Ca (main.js:1:620236)
    at K_ (main.js:1:626284)
    at M_ (main.js:1:620096)
    at Ca (main.js:1:620107)
    at W_ (main.js:1:619664)

**Comment by jbrazzorotto** [comment]
same

ERROR TypeError: ({get default(value}) is not a constructor
    initMasonry ngx-masonry-gallery.mjs:127
    ngAfterViewInit ngx-masonry-gallery.mjs:53

**Comment by pareshgami** [comment]
![Screenshot 2022-12-24 at 3 50 00 PM](https://user-images.githubusercontent.com/6784115/209431659-84f14f5a-8bb2-4a5c-a25c-4a969eaa0a55.png)

Getting this error.

**Comment by StuBramley** [comment]
> ![Screenshot 2022-12-24 at 3 50 00 PM](https://user-images.githubusercontent.com/6784115/209431659-84f14f5a-8bb2-4a5c-a25c-4a969eaa0a55.png)
> 
> Getting this error.

Also getting this problem

**Comment by adventmedia** [comment]
likewise
